### ISSUE TITLE
Candidatos para Senador e Governador estão trocados

### ISSUE THREAD

**Issue by rnmourao** [Cepesp-Fgv/cepesp-python#2]
Ao usar a função voto_x_candidatos, percebi que os candidatos para governador aparecem na pesquisa por senador e vice-versa.

**Comment by Cepesp-Fgv** [comment]
Problema resolvido. Os códigos dos cargos estavam trocados. O código para Senador é 5 e para Governador é 3.

**Comment by rnmourao** [comment]
Ainda com problema, mesmo depois de limpar o cache.
![captura de tela de 2017-11-14 10-56-38](https://user-images.githubusercontent.com/16841587/32781054-b4a64e88-c92a-11e7-8bcc-2f11e913549b.png)
