### ISSUE TITLE
Candidatos para Senador e Governador continuam trocados 

### ISSUE THREAD

**Issue by rnmourao** [Cepesp-Fgv/cepesp-python#3]
Ainda com problema, mesmo depois de limpar o cache.
![captura de tela de 2017-11-14 10-56-38](https://user-images.githubusercontent.com/16841587/32781490-61909fc6-c92c-11e7-9869-883413adfa8b.png)

**Comment by Cepesp-Fgv** [comment]
Na sua versão da biblioteca, os códigos dos cargos estão exatamente assim?
![image](https://user-images.githubusercontent.com/28055677/33304263-8a5f1e40-d3e6-11e7-85da-9344112d27ca.png)

**Comment by rnmourao** [comment]
Falha minha. Não vi a atualização do código.
