### ISSUE TITLE
Campos de CPF de candidatos estão com nomes

### ISSUE THREAD

**Issue by rnmourao** [Cepesp-Fgv/cepesp-python#4]
![captura de tela de 2017-11-26 11-06-36](https://user-images.githubusercontent.com/16841587/33240222-f3265158-d299-11e7-9774-99dea81eed50.png)

**Comment by Cepesp-Fgv** [comment]
Ano 2010 estava com problemas de formatação que causaram um deslocamento nas colunas. Problema resolvido.
