### ISSUE TITLE
Filtro por Estado não está funcionando

### ISSUE THREAD

**Issue by rnmourao** [Cepesp-Fgv/cepesp-python#6]
![captura de tela de 2017-12-15 14-06-14](https://user-images.githubusercontent.com/16841587/34050193-2af4a90c-e1a1-11e7-910b-5d7ebc2678bd.png)

**Comment by Cepesp-Fgv** [comment]
Corrigido. O problema estava na API Rest. O parametro uf_filter não estava funcionando devidamente em todos os casos de agregação regional.
